=== pontsci/csci-4850-xml-projects/assignment6_masonfleming.dtd
<!ELEMENT assignment6_masonfleming (employee_table,works_table,company_table)>
<!ELEMENT employee_table (employee*)>
<!ELEMENT employee (firstname,middleinitial,lastname,street,city,gender)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middleinitial (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT works_table (worker*)>
<!ELEMENT worker (firstname,middleinitial,lastname,companyname,salary)>
<!ELEMENT companyname (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT company_table (company*)>
<!ELEMENT company (companyname, city)>

=== pontsci/csci-4850-xml-projects/src/assignment6_masonfleming.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE assignment6_masonfleming SYSTEM "assignment6_masonfleming.dtd">
<assignment6_masonfleming>
    <employee_table>
        <employee>
            <firstname>Susan</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Anderson</lastname>
            <street>108th</street>
            <city>Omaha</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Dan</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Brady</lastname>
            <street>P street</street>
            <city>Lincoln</city>
            <gender>M</gender>
        </employee>
        <employee>
            <firstname>Peter</firstname>
            <middleinitial>K</middleinitial>
            <lastname>Chen</lastname>
            <street>124th</street>
            <city>Omaha</city>
            <gender>M</gender>
        </employee>
        <employee>
            <firstname>Ann</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Clemson</lastname>
            <street>O</street>
            <city>Lincoln</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Mary</firstname>
            <middleinitial>K</middleinitial>
            <lastname>Dale</lastname>
            <street>132th</street>
            <city>Omaha</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Mary</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Gill</lastname>
            <street>P street</street>
            <city>Lincoln</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Susan</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Harrison</lastname>
            <street>Old Mill</street>
            <city>Omaha</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Kim</firstname>
            <middleinitial>A</middleinitial>
            <lastname>Jackson</lastname>
            <street>178th</street>
            <city>Omaha</city>
            <gender>F</gender>
        </employee>
        <employee>
            <firstname>Pat</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Jason</lastname>
            <street>8th</street>
            <city>C.Bluffs</city>
            <gender>M</gender>
        </employee>
        <employee>
            <firstname>Paul</firstname>
            <middleinitial>T</middleinitial>
            <lastname>Kumar</lastname>
            <street>Dodge</street>
            <city>Omaha</city>
            <gender>M</gender>
        </employee>
    </employee_table>
    <works_table>
        <worker>
            <firstname>Susan</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Anderson</lastname>
            <companyname>Mutual of Omaha</companyname>
            <salary>48000</salary>
        </worker>
        <worker>
            <firstname>Dan</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Brady</lastname>
            <companyname>FDR</companyname>
            <salary>42000</salary>
        </worker>
        <worker>
            <firstname>Peter</firstname>
            <middleinitial>K</middleinitial>
            <lastname>Chen</lastname>
            <companyname>FDR</companyname>
            <salary>53000</salary>
        </worker>
        <worker>
            <firstname>Ann</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Clemson</lastname>
            <companyname>First Bank</companyname>
            <salary>39000</salary>
        </worker>
        <worker>
            <firstname>Mary</firstname>
            <middleinitial>K</middleinitial>
            <lastname>Dale</lastname>
            <companyname>Mutual of Omaha</companyname>
            <salary>58000</salary>
        </worker>
        <worker>
            <firstname>Mary</firstname>
            <middleinitial>L</middleinitial>
            <lastname>Gill</lastname>
            <companyname>Union Pacific</companyname>
            <salary>48700</salary>
        </worker>
        <worker>
            <firstname>Susan</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Harrison</lastname>
            <companyname>Union Pacific</companyname>
            <salary>54320</salary>
        </worker>
        <worker>
            <firstname>Kim</firstname>
            <middleinitial>A</middleinitial>
            <lastname>Jackson</lastname>
            <companyname>FDR</companyname>
            <salary>68000</salary>
        </worker>
        <worker>
            <firstname>Pat</firstname>
            <middleinitial>M</middleinitial>
            <lastname>Jason</lastname>
            <companyname>FDR</companyname>
            <salary>83000</salary>
        </worker>
        <worker>
            <firstname>Paul</firstname>
            <middleinitial>T</middleinitial>
            <lastname>Kumar</lastname>
            <companyname>FDR</companyname>
            <salary>44000</salary>
        </worker>
    </works_table>
    <company_table>
        <company>
            <companyname>First Bank</companyname>
            <city>Omaha</city>
        </company>
        <company>
            <companyname>FDR</companyname>
            <city>Omaha</city>
        </company>
        <company>
            <companyname>Lincoln Star</companyname>
            <city>Lincoln</city>
        </company>
        <company>
            <companyname>Mutual of Omaha</companyname>
            <city>Omaha</city>
        </company>
        <company>
            <companyname>Union Pacific</companyname>
            <city>Omaha</city>
        </company>
    </company_table>
</assignment6_masonfleming>
